module Emulator.CPU where

import Emulator.Types

import Control.Applicative
import Data.Bits
import Control.Lens
import Data.Default.Class
import Prelude

data CPUMode = User
             | FIQ
             | IRQ
             | Supervisor
             | Abort
             | Undefined
             | System
  deriving (Show, Read, Eq)

data RegisterX =
  -- Registers R0 - R12 are all general purpose registers
  -- In non-thumb mode all registers are available for any purpose
  -- In thumb mode only registers R0 - R7 are available, whereas
  --  R8 - R12 are only accessible from certain instructions
  R0 RegisterVal
  | R1 RegisterVal
  | R2 RegisterVal
  | R3 RegisterVal
  | R4 RegisterVal
  | R5 RegisterVal
  | R6 RegisterVal
  | R7 RegisterVal
  | R8 RegisterVal
  | R9 RegisterVal
  | R10 RegisterVal
  | R11 RegisterVal
  | R12 RegisterVal
  | R13 RegisterVal  -- SP Register
                     -- Stack pointer in thumb mode, SP or GP in ARM mode
  | R14 RegisterVal  -- LR Register
                     -- Return address after branch with
                     -- link (LB instruction), or GP in ARM
  | R15 RegisterVal  -- PC Register
                     -- Program counter, contains address to currently executing
                     -- statement.
  | CPSR RegisterVal -- Flags and CPU state register

data Flags = Flags -- Status Register
  { _flagsSign :: Bool
  , _flagsZero :: Bool
  , _flagsCarry :: Bool
  , _flagsOverflow :: Bool
  , _flagsStickyOverflow :: Bool
  , _flagsIrqDisable :: Bool
  , _flagsFiqDisable :: Bool
  , _flagsStateBit :: Bool }
  deriving (Show, Read, Eq)

makeFields ''Flags

instance Default Flags where
  def = Flags False False False False False False False False

applyFlags :: Flags -> MWord -> MWord
applyFlags = undefined

extractFlags :: MWord -> Flags
extractFlags =
  Flags <$> tb 31
        <*> tb 30
        <*> tb 29
        <*> tb 28
        <*> tb 27
        <*> tb 7
        <*> tb 6
        <*> tb 5
  where tb = flip testBit

data Registers = Registers
  { _registersR0 :: MWord
  , _registersR1 :: MWord
  , _registersR2 :: MWord
  , _registersR3 :: MWord
  , _registersR4 :: MWord
  , _registersR5 :: MWord
  , _registersR6 :: MWord
  , _registersR7 :: MWord
  , _registersR8 :: MWord
  , _registersR9 :: MWord
  , _registersR10 :: MWord
  , _registersR11 :: MWord
  , _registersR12 :: MWord
  , _registersR13 :: MWord
  , _registersR14 :: MWord
  , _registersR15 :: MWord
  , _registersCpsr :: Flags }
  deriving (Show, Read, Eq)

makeFields ''Registers

instance Default Registers where
  def = Registers 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 def

data Shifted a = Shifted Shift a
  deriving (Show, Read, Eq)

data Shift = Shift
  deriving (Show, Read, Eq)

data Condition = EQ -- Equal
               | NE -- Not equal
               | CS -- Carry set
               | CC -- Carry clear
               | MI -- Negative
               | PL -- Positive
               | VS -- Overflow
               | VC -- No overflow
               | HI -- Unsigned higher
               | LS -- Unsigned lower or same
               | GE -- Signed greater than or equal
               | LT -- Less than
               | GT -- Greater than
               | LE -- Less than or equal
               | AL -- Always (unconditional)
  deriving (Show, Read, Eq, Enum, Bounded)

conditionFromWord :: Byte -> Maybe Condition
conditionFromWord = fromWord

fromWord :: forall a. (Enum a, Bounded a) => Byte -> Maybe a
fromWord b =
  if fromIntegral b > maxWord then Nothing else Just $ toEnum $ fromIntegral b
    where
      maxWord = fromEnum (maxBound :: a)

data Interrupt = Reset                -- Probably won't be used
               | UndefinedInstruction -- Used if a bad instruction is found
               | SoftwareInterrupt    -- Interrupts that can be generated by the programmer
               | PrefetchAbort        -- The *Abort interrupts probably won't be used as they are
               | DataAbort            --   for virtual memory systems, which the GBA doesn't use.
               | NormalInterrupt      -- Standard interrupts
               | FastInterrupt        -- Fast (standard) interrupts
   deriving (Show, Read, Eq)
